### ISSUE TITLE
img inside a figure will create an opening and closing img tag

### ISSUE THREAD

**Issue by creutz** [Masterminds/html5-php#222] opened 2023-01-11 14:49 UTC
`<figure><img src=""></figure>` will create `<figure><img src=""></img></figure>`. Is this by design?

**Comment by goetas** [comment] 2023-01-11 19:54
I have tried and i'm not able to reproduce it. for me  `<figure><img src=""></figure>` it is serialized correctly as `<figure><img src=""/></figure>`.

can you please provide a failing test case?

**Comment by stof** [comment] 2023-01-12 09:04
I cannot reproduce this when using `$html5->saveHTML($dom);`

Using `$dom->saveHTML()` indeed produces `<figure><img src=""></img></figure>`, but this is because it does not use the HTML5 renderer. The built-in PHP HTML renderer uses XHTML, not HTML5.

**Comment by ohader** [comment] 2023-01-12 09:23
I also was not able to reproduce this behavior.

```php
<?php
require 'vendor/autoload.php';
$html5 = new Masterminds\HTML5();
$string = '<figure><img src=""></figure>';
$doc = $html5->loadHTML($string);
echo $html5->saveHTML($doc);
```
outputs
```html
<!DOCTYPE html>
<html><figure><img src=""></figure></html>
```

---

By using `DOMDocumentFragment` it is possible to focus on the submitted fragment only.

```php
<?php
require 'vendor/autoload.php';
$html5 = new Masterminds\HTML5();
$string = '<figure><img src=""></figure>';
$fragment = $html5->parseFragment($string);
echo $html5->saveHTML($fragment);
```
outputs
```html
<figure><img src=""></figure>
```

**Comment by goetas** [comment] 2023-01-19 12:41
closing as "can not reproduce"

**Closed by goetas** 2023-01-19 12:41 UTC
Labels: question
