### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lofesa** [Masterminds/html5-php#212] opened 2022-03-23 12:17 UTC
Hi
I come here to ask a, maybe, dumb question.
I used a WP plugin that uses this library to make changes to the html. This html contain inlined svg like:

`< svg xmlns= "https://www.w3.org/2000/svg" some stuff here ></svg>`

After get parsed this becomes:

`< svg some stuff here /></svg>`

Is there any way to preserve the xmlns attribute and don´t set the autoclosig / ?

Thx in advance.

**Comment by Lofesa** [comment] 2023-01-12 07:42
The plugin uses `html5->saveHTML($dom);`

**Comment by Lofesa** [comment] 2023-01-12 12:35
Yes this url `https://intersindicalrm.org/la-intersindical-se-extiende-al-servicio-murciano-de-salud/`
These icons in the image have the xmlns attribute but get stripped
<img width="1280" alt="Captura de pantalla 2023-01-12 133330" src="https://user-images.githubusercontent.com/22342793/212067792-19f1c2d9-c5a0-4d73-af81-8cdacc985866.png">

**Comment by stof** [comment] 2023-01-12 13:22
When I take this URL, the SVG icons *don't* have the xmlns attribute.

**Comment by Lofesa** [comment] 2023-01-12 13:27
Yes, because are striped

For example, the arrow up svg, the original is

`$output = '<svg viewBox="0 0 330 512" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><path d="M305.863 314.916c0 2.266-1.133 4.815-2.832 6.514l-14.157 14.163c-1.699 1.7-3.964 2.832-6.513 2.832-2.265 0-4.813-1.133-6.512-2.832L164.572 224.276 53.295 335.593c-1.699 1.7-4.247 2.832-6.512 2.832-2.265 0-4.814-1.133-6.513-2.832L26.113 321.43c-1.699-1.7-2.831-4.248-2.831-6.514s1.132-4.816 2.831-6.515L158.06 176.408c1.699-1.7 4.247-2.833 6.512-2.833 2.265 0 4.814 1.133 6.513 2.833L303.03 308.4c1.7 1.7 2.832 4.249 2.832 6.515z" fill-rule="nonzero" /></svg>';`

**Comment by stof** [comment] 2023-01-12 13:31
If you give me a URL which shows the HTML being  the *output* of the library, that's not a reproducing case.

**Comment by stof** [comment] 2023-01-12 13:32
The `xmlns` is not rendered in the output of the library because it is useless when using a `svg` tag inside HTML: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg

**Comment by goetas** [comment] 2024-07-17 13:58
closing as not able to reproduce

**Closed by goetas** 2024-07-17 13:58 UTC
