### ISSUE TITLE
image within inline svg breaks system

### ISSUE THREAD

**Issue by jschoder** [Masterminds/html5-php#129] opened 2017-05-09 08:02 UTC
I have a website with inline SVGs, some of them include a image-tag, which isn't an empty tag but a separate open and close tag. Your function Parser/DOMTreeBuilder.startTag just overrides image with img which doesn't allow a separate closing tag and therefore fails.

I totally get why img is identical to image in normal html. But the replacement shouldn't happen when the tag is inside an inline svg. For now I "fixed" the issue by uncommenting the image-img-replacement.

**Comment by goetas** [comment] 2017-05-09 08:40
Does it mean that when we are in SVG mode, `image` should not be replaced by `img` ? is this in the HTML5 spec?

**Comment by goetas** [comment] 2017-05-09 09:41
@jschoder  
Are you sure about this? 

See https://github.com/Masterminds/html5-php/commit/4b75717ce1692ef87704beaa213c9744eccea662 that  tries to reproduce the case you said, and as you can see on travis (https://travis-ci.org/Masterminds/html5-php/builds/230278543) the build is green

**Comment by MichaelHeerklotz** [comment] 2017-08-18 19:15
<svg><image></image></svg>
This is the problematic case.

**Comment by goetas** [comment] 2017-08-23 09:56
@MichaelHeerklotz and @jschoder can you point me to the docs where is specified that `<svg><image/></svg>` is not valid?

I've used the https://validator.w3.org/nu/#textarea validator, and the following document looks to be valid:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>foo</title>
    </head>
    <body>
        <svg>
            <image height="10"  width="10"/>
        </svg>
    </body>
</html>
```

Closing the issue because of it.

Feel free to comment, and if the issue looks still there, will re-open it.

**Closed by goetas** 2017-08-23 09:56 UTC
Labels: Waiting feedback

**Comment by MichaelHeerklotz** [comment] 2017-08-23 14:12
```
<!DOCTYPE html>
<html>
    <head>
        <title>foo</title>
    </head>
    <body>
        <svg>
            <image height="10" width="10">
        </svg>
    </body>
</html>
```
html5-php: No errors
W3C Validator: Error: End tag svg did not match the name of the current open element (image).

```
<!DOCTYPE html>
<html>
    <head>
        <title>foo</title>
    </head>
    <body>
        <svg>
            <image height="10" width="10"/>
        </svg>
    </body>
</html>
```
html5-php: Line 0, Col 0: Could not find closing tag for image
W3C Validator: Error: No errors

```
<!DOCTYPE html>
<html>
    <head>
        <title>foo</title>
    </head>
    <body>
        <svg>
            <image height="10" width="10"></image>
        </svg>
    </body>
</html>
```
html5-php: Line 0, Col 0: Could not find closing tag for image
W3C Validator: Error: No errors

**Comment by goetas** [comment] 2017-08-23 14:21
@MichaelHeerklotz  which version are you using? see https://github.com/Masterminds/html5-php/blob/0a00d47cd6712cdb4e4190d436303acba9b8a49d/test/Html5Test.php#L32 and https://travis-ci.org/Masterminds/html5-php/builds/267601453

**Comment by MichaelHeerklotz** [comment] 2017-08-23 20:37
@goetas latest branch 2.x from today. I check the errors with:
```
    $htmlParser = new \Masterminds\HTML5();
    $htmlDocument = $htmlParser->loadHTML($html);
    if ($htmlParser->hasErrors()) {
        var_dump($htmlParser->getErrors());
    }
```

**Comment by goetas** [comment] 2017-08-25 09:33
fixed with https://github.com/Masterminds/html5-php/pull/133

**Comment by mat-hew1** [comment] 2021-08-24 12:35
The current version 2.7.5 still returns svg as text node:
```html
<ul id="nav1" class="nav1main">
    <li>
        <a href="/" class="logo-image">
            &lt;svg id="logo-mobile"&gt;
                &lt;image href="logo-mobile.svg" width="100%" height="100%" /&gt;
            &lt;/svg&gt;
        </a>
    </li>
</ul>
```
Source:
```html
<ul id="nav1" class="nav1main">
    <li>
        <a href="/" class="logo-image">
            <svg id="logo-mobile">
                <image href="logo-mobile.svg" width="100%" height="100%"></image>
            </svg>
        </a>
    </li>
</ul>
```
Equal, if image with separate closing tag or self-closing.
